### ISSUE TITLE
Pipenv Support

### ISSUE THREAD

**Issue by isidentical** [vigo/django2-project-template#20]
It is more organized than using a custom directory called `requirements/` and a file called `.python_version`, also it provides virtual env functionality.

**Comment by vigo** [comment]
Why don't you add this feature for all of us? Love to merge you PR here :)

**Comment by vigo** [comment]
ps: `.python-version` is `pyenv` related file. not my invention :)

**Comment by isidentical** [comment]
I'll try.

**Comment by isidentical** [comment]
I got a working (~just tested in one case~) demo but i dont think i can adapt my self to this repo's build system. I think it would be better to convert pipenv by someone who knows what is what. 

[The demo](https://github.com/isidentical/django2-project-template)
